### ISSUE TITLE
Problem parsing type annotation with siblings params

### ISSUE THREAD

**Issue by rogeriochaves** [stil4m/elm-syntax#14]
elm-syntax is parsing type annotations like `Dict String Int` as if it were nested, like `Dict (String Int)`

I've written a failing test that you can add to `tests/Elm/Parser/TypeAnnotationTests.elm` to verify, but I couldn't fix the problem:

```elm
test "parse type with multiple params" <|
    \() ->
        parseFullStringWithNullState "Dict String Int" Parser.typeAnnotation
            |> Maybe.map noRangeTypeReference
            |> Expect.equal
                (Just
                    ( emptyRange
                    , Typed []
                        "Dict"
                        [ ( emptyRange, Typed [] "String" [] )
                        , ( emptyRange, Typed [] "Int" [] )
                        ]
                    )
                )
```

**Comment by stil4m** [comment]
Thanks. I'll look into this.

**Comment by rogeriochaves** [comment]
This issue is already fixed right? I'll close it
Hey, since you are here, thank you so very much for the quickly responses, merges, publishing and even this quick fix

Here is what I've built using your library :)

https://github.com/rogeriochaves/spades

**Comment by stil4m** [comment]
It is fixed and released. It was a simple fix, since I've already encountered it on the 0.19 branch. Thank you for creating descriptive issues and concise to-the-point PRs ;).

Cool! It is always nice to see that if you build something, someone is using it :). If you need any support on the lib (elm-syntax or structured-writer) you can also ping me on Slack.
