### ISSUE TITLE
Using the parser in CLI

### ISSUE THREAD

**Issue by frou** [stil4m/elm-syntax#16]
Hi there - Could this project conceivably be used to write the AST of an elm file to standard-output as JSON? Or am I barking up the wrong tree?

**Comment by stil4m** [comment]
@frou Yes you can use it this way. `elm-analyse` uses this to cache parsing results.  You could start [here](http://package.elm-lang.org/packages/stil4m/elm-syntax/latest/Elm-Parser) to parse a file, and then [this](http://package.elm-lang.org/packages/stil4m/elm-syntax/4.0.2/Elm-Json-Encode) to create a JSON value.

Having/building this functionality is not part of the lib (and not possible since it is published), but tools can use this lib to provide this kind of functionality. See the readme for examples.

**Comment by frou** [comment]
Great - thanks for the pointers.
